---
deployment:
  tasks:
    - rm -rf /home/suradnhs/public_html/
    - cd /home/suradnhs/
    - mkdir public_html
    - chmod 750 public_html
    - export DEPLOYPATH=/home/suradnhs/public_html/
    - /bin/cp -r * $DEPLOYPATH