---
deployment:
  tasks:
    - rm -rf /home/suradnhs/public_html/
    - cd /home/suradnhs/
    - mkdir public_html
    - chmod public_html 750
    - export DEPLOYPATH=/home/suradnhs/public_html/
    - /bin/cp -r * $DEPLOYPATH
    - ln -s /home/suradnhs/public /home/suradnhs/public_html/